version: "2"

checks:
  method-lines:
    config:
      threshold: 50

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
  rubocop:
    enabled: true

exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "**/*_test.go"
  - "__setup__/"
  - "**/__tests__/"
