# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.0

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:latest-node-browsers
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: developer
  postgres: &postgres
    image: circleci/postgres:12.1-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: developer_test_db
  # glue: &glue
  #   image: owasp/glue
  dependency-check: &dependency-check
    image: owasp/dependency-check:latest

jobs:
  build:
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle cache
      - restore_cache:
          keys:
            - developer-dependencies-{{ checksum "Gemfile.lock" }}
            - developer-dependencies-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: developer-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - developer-yarn-{{ checksum "yarn.lock" }}
            - developer-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      # Store yarn / webpacker cache
      - save_cache:
          key: developer-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build-dependency-check:
    docker:
      - *dependency-check
    steps:
      - restore_cache:
          keys:
            - developer-dependency-check
      - run:
          name: owasp/dependency-check
          command: |
            /usr/share/dependency-check/bin/dependency-check.sh --updateonly
      - save_cache:
          key: developer-dependency-check
          paths:
            - /usr/share/dependency-check/data
  dependency-check:
    docker:
      - *default_docker_ruby_executor
      - *dependency-check
    steps:
      - checkout
      - setup_remote_docker
      #- run:
      #    command: mkdir -p /usr/share/dependency-check/data
      - restore_cache:
          keys:
            - developer-dependencies-{{ checksum "Gemfile.lock" }}
            - developer-dependencies-
      - restore_cache:
          keys:
            - developer-yarn-{{ checksum "yarn.lock" }}
            - developer-yarn-
      - restore_cache:
          keys:
            - developer-dependency-check
      - run:
          name: owasp/dependency-check
          command: |
            docker run --volume /tmp/dependency-check:/report \
              owasp/dependency-check:latest --enableExperimental --project rubyonrails-template --out /report --scan .
      - store_artifacts:
          path: /tmp/dependency-check/report
          destination: dependency-check
  test:
    docker:
      - *default_docker_ruby_executor
      - *postgres
      # - *glue
    # working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - developer-dependencies-{{ checksum "Gemfile.lock" }}
            - developer-dependencies-
      - restore_cache:
          keys:
            - developer-yarn-{{ checksum "yarn.lock" }}
            - developer-yarn-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Database setup
      - run:
          name: Database setup
          command: bundle exec rake db:create
      # run security test!
      # - bundle-audit
      - run:
          name: Bundle Audit
          command: bundle exec bundle-audit check --update
      # - brakeman
      - run:
          name: brakeman
          command: bundle exec brakeman
      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- build-dependency-check
      - dependency-check:
          requires:
            - build
            #- build-dependency-check
      - test:
          requires:
            - build
